./rad dataset/test/a08_s07_e01_skeleton_proj.txt test custom
./rad dataset/test/a08_s07_e02_skeleton_proj.txt test custom
./rad dataset/test/a08_s08_e01_skeleton_proj.txt test custom
./rad dataset/test/a08_s08_e02_skeleton_proj.txt test custom
./rad dataset/test/a08_s09_e01_skeleton_proj.txt test custom
./rad dataset/test/a08_s09_e02_skeleton_proj.txt test custom
./rad dataset/test/a08_s10_e01_skeleton_proj.txt test custom
./rad dataset/test/a08_s10_e02_skeleton_proj.txt test custom
./rad dataset/test/a10_s07_e01_skeleton_proj.txt test custom
./rad dataset/test/a10_s07_e02_skeleton_proj.txt test custom
./rad dataset/test/a10_s08_e01_skeleton_proj.txt test custom
./rad dataset/test/a10_s08_e02_skeleton_proj.txt test custom
./rad dataset/test/a10_s09_e01_skeleton_proj.txt test custom
./rad dataset/test/a10_s09_e02_skeleton_proj.txt test custom
./rad dataset/test/a10_s10_e01_skeleton_proj.txt test custom
./rad dataset/test/a10_s10_e02_skeleton_proj.txt test custom
./rad dataset/test/a12_s07_e01_skeleton_proj.txt test custom
./rad dataset/test/a12_s07_e02_skeleton_proj.txt test custom
./rad dataset/test/a12_s08_e01_skeleton_proj.txt test custom
./rad dataset/test/a12_s08_e02_skeleton_proj.txt test custom
./rad dataset/test/a12_s09_e01_skeleton_proj.txt test custom
./rad dataset/test/a12_s09_e02_skeleton_proj.txt test custom
./rad dataset/test/a12_s10_e01_skeleton_proj.txt test custom
./rad dataset/test/a12_s10_e02_skeleton_proj.txt test custom
./rad dataset/test/a13_s07_e01_skeleton_proj.txt test custom
./rad dataset/test/a13_s07_e02_skeleton_proj.txt test custom
./rad dataset/test/a13_s08_e01_skeleton_proj.txt test custom
./rad dataset/test/a13_s08_e02_skeleton_proj.txt test custom
./rad dataset/test/a13_s09_e01_skeleton_proj.txt test custom
./rad dataset/test/a13_s09_e02_skeleton_proj.txt test custom
./rad dataset/test/a13_s10_e01_skeleton_proj.txt test custom
./rad dataset/test/a13_s10_e02_skeleton_proj.txt test custom
./rad dataset/test/a15_s07_e01_skeleton_proj.txt test custom
./rad dataset/test/a15_s07_e02_skeleton_proj.txt test custom
./rad dataset/test/a15_s08_e01_skeleton_proj.txt test custom
./rad dataset/test/a15_s08_e02_skeleton_proj.txt test custom
./rad dataset/test/a15_s09_e01_skeleton_proj.txt test custom
./rad dataset/test/a15_s09_e02_skeleton_proj.txt test custom
./rad dataset/test/a15_s10_e01_skeleton_proj.txt test custom
./rad dataset/test/a15_s10_e02_skeleton_proj.txt test custom
./rad dataset/test/a16_s07_e01_skeleton_proj.txt test custom
./rad dataset/test/a16_s07_e02_skeleton_proj.txt test custom
./rad dataset/test/a16_s08_e01_skeleton_proj.txt test custom
./rad dataset/test/a16_s08_e02_skeleton_proj.txt test custom
./rad dataset/test/a16_s09_e01_skeleton_proj.txt test custom
./rad dataset/test/a16_s09_e02_skeleton_proj.txt test custom
./rad dataset/test/a16_s10_e01_skeleton_proj.txt test custom
./rad dataset/test/a16_s10_e02_skeleton_proj.txt test custom